# AlertModeMechanics
# A mod by Lucky Rapidflower (2025) for bmn's ASI plugin
# Changes various mechanics related to alert modes.
#
# NoExplosionInstaAlert=Yes prevents instant alerts on regular guards hearing an explosion.
# Instead, they will react akin to hearing a gunshot: by radioing an alert.
# If a guard is immediately caught in the blast, they will instead radio a caution after recovering.
# As a result, explosives (especially stun grenades with their long effect radius) are more useful during stealth sections.
#
# AlertModePersistsOnContinue=Yes will set the alert mode to what it was at the beginning of an area upon using a continue.
#
# AlertModeOnExitingAreaWithAlarmedGuard=Yes will:
# 1. cause an alert on leaving an area when a guard is radioing an alert
# (this will also increment the alert stat even if the next area prevents/ends alerts),
# 2. cause a caution if a guard is radioing a caution or if they are alarmed but not (yet) radioing an alert.
# As a result, stealth sections are a bit more realistic and abusing area loads to avoid alerts/cautions is not so viable.
#
# NumberOfAresTiedToCaution= will require the player to pass the given number of areas for caution to end
# instead of it being based on time. As a result, the player can no longer hide and wait to end cautions.
# Set this to 0 or less to disable this setting.

[AlertModeMechanics]
Enabled=Yes
#NoExplosionInstaAlert=Yes
#AlertModePersistsOnContinue=Yes
#AlertModeOnExitingAreaWithAlarmedGuard=Yes
#NumberOfAreasTiedToCaution=4