# A mod by Lucky Rapidflower (2025) for bmn's ASI plugin
# Currently contains Lucky's Remix v0.3:
# A challenge mod that alters items, starting inventories, pickups and alert mode mechanics.
# Areas may be subtly changed in other ways too and a certain exploit has been fixed...
# This mod has been primarily balanced around (European) Extreme, but please play it on the difficulty you find the most enjoyable.
# (Hard can still keep stealth sections fairly tricky while making boss fights more manageable)
# v0.3 covers the Tanker chapter and the Plant chapter up to the Harrier boss fight.

[Challenge]
Enabled=Yes