# A mod by Lucky Rapidflower (2025) for bmn's ASI plugin
#
#
# Currently only contains Lucky's Remix v1.0:
#
# A challenge mod that alters items, starting inventories, pickups, and alert mode mechanics.
# Areas may be changed in other ways too, and certain exploits have been fixed...
#
# This mod has been primarily balanced around (European) Extreme, but please play it on the difficulty you find the most enjoyable.
# (Hard can still keep stealth sections fairly tricky while making boss fights more manageable.)
#
# You have my blessing to use turbo during Solidus's torture sequence.
#
# v1.0 covers the main game (Tanker-Plant).

[Challenge]
Enabled=Yes